Docs Update
open-frames/docs pull request #9
Opened 2024-08-25 16:58 UTC by fabriguespe

Updated docs 
- Quickstart
- Frames.js
- Frog
- OnchainKit

2024-08-26 13:58 UTC, davidfurlong requested changes

2024-08-26 13:58 UTC, davidfurlong commented on pages/quickstart/frames-js.mdx
> +Discover how Frog seamlessly incorporates XMTP payloads
Frames.js

2024-08-26 13:58 UTC, davidfurlong commented on pages/quickstart/frames-js.mdx
> +- [Quickstart](https://github.com/ephemeraHQ/open-frames-starter-framesjs/): OnchainKit quickstart that integrates XMTP.
Frames.js quickstart

2024-08-26 13:58 UTC, davidfurlong commented on pages/quickstart/frames-js.mdx
> +- [Official Docs](https://framesjs.org/reference/js/xmtp): Official Frames.js Documentation.
link is outdated; https://framesjs.org/guides/open-frames is probably best atm

2024-08-26 13:58 UTC, davidfurlong commented on pages/quickstart/frames-js.mdx
> +} from "@coinbase/onchainkit/xmtp";
wrong lib & example

2024-08-28 17:17 UTC, fabriguespe commented
Thks @davidfurlong ! Changes made

2024-08-29 08:40 UTC, davidfurlong approved these changes
@fabriguespe I made some changes to the frames.js guide directly

2024-08-29 08:40 UTC, davidfurlong commented on pages/quickstart/frames-js.mdx
> +- [Frames.js quickstart](https://github.com/ephemeraHQ/open-frames-starter-framesjs/): OnchainKit quickstart that integrates XMTP.
`OnchainKit quickstart` -> `Frames.js quickstart`

2024-08-29 08:40 UTC, davidfurlong commented on pages/quickstart/frames-js.mdx
> +- [Frames.js quickstart](https://github.com/ephemeraHQ/open-frames-starter-framesjs/): OnchainKit quickstart that integrates XMTP.
Outdated

2024-08-29 10:02 UTC, fabriguespe commented
@davidfurlong nice. I dont have access to the repo or team to be able to merge.

2024-08-30 17:12 UTC, merged